### ISSUE TITLE
port/make chrome version

### ISSUE THREAD

**Issue by ethan-egerton** [ethan-egerton/spotify2tabs#1]

**Comment by TheRecklessDoctor** [comment]
Let me see if I can help.

**Comment by ethan-egerton** [comment]
Give it a go, I'm really not sure if it needs the code needs to be changed to work on Chrome.
If you do give it a go, let me know how it goes or send a PR. Thanks!

**Comment by ethan-egerton** [comment]
Closing as information given in #6 solves this issue.
